### ISSUE TITLE
5 dimension hard limit to DWA object plot in qt

### ISSUE THREAD

**Issue by Sigarrigou** [PyMoDAQ/pymodaq_data#19]
I am trying to plot 2D datas with 3 navigation axes with qt. 1D with 3 Nav_axes works perfectly. 
There seems to be a built-in limit of 4 dimensions for a Data_with_axes plot using qt. (Error message : "Ndarray of dim: 5 cannot be plotted using a DataND") 
Is there a way to overcome this limitation ?

I here join a minimal python script reproducing the error message.
[5D_dim_error_example.txt](https://github.com/user-attachments/files/17979707/5D_dim_error_example.txt)

**Comment by seb5g** [comment]
Well I don't know how we could render such data? any ideas?

**Comment by Sigarrigou** [comment]
I would think of an extension from the method for 2 signal axes and 1 or 2 navigation axes, and this could even be extended to arbitrary number of navigation axes ? 
For instance something like the following photomontage
![image](https://github.com/user-attachments/assets/fd2f0ada-feb8-4608-b7c4-f006c70b0fa5)

**Comment by seb5g** [comment]
yes you're right, there was a mistake preventing this kind of plot. There are no more limitations now with https://github.com/PyMoDAQ/pymodaq_gui/pull/20
