### ISSUE TITLE
Class property "name" in "SerializableFactory" deprecated

### ISSUE THREAD

**Issue by BenediktBurger** [PyMoDAQ/pymodaq_data#8]
Pylance tells me that: "Class properties are deprecated in Python 3.11 and will not be supported in Python 3.13"
regarding the class property `SerializableFactory.name` in `factory.py`.

**Comment by seb5g** [comment]
you're right and moreover this property is not used anyway. I will just remove it from there!

**Comment by seb5g** [comment]
closed by PR #14
